name: LAMP deployment

on:
  workflow_dispatch:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the sources
      uses: actions/checkout@v2
    - name: Ansible Lint
      uses: ansible-community/ansible-lint-action@v6.0.2
      with: 
        targets: |
          ansible/playbook.yml
          ansible/inventory.yml

        #args: "-c ansible/.ansible-lint"

    - name: Publish Playbook Artifact    
      uses: actions/upload-artifact@v2
      with:
        name: playbooks
        path: anisble

  deploy_to_test:
    name: Deploy to test
    runs-on: ubuntu-latest
    needs: linting

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: playbooks
        path: anisble


    - uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: playbook.yml
        directory: anisble
        options: |
          --inventory inventory-test.yml
          --extra-vars "test_ssh_password=${{Secrets.TEST_SSH_PASSWORD}}"    
